# Generated by Django 5.1.5 on 2025-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parcelamento',
            field=models.CharField(max_length=50),
        ),
    ]
