# Generated by Django 5.1.5 on 2025-02-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_parcelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentual_desconto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco_sem_desconto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
