# Generated by Django 5.1.5 on 2025-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_imagem_alter_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parcelamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
